spring:
  application:
    name: '@project.name@'
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
fileName: feladat_1.csv